### ISSUE TITLE
Existing DB using 'get_items'

### ISSUE THREAD

**Issue by switchtower** [wpj-cz/django-caldav#1]
Hello,

I was curious if there was an easy way to add the ability to use an existing DB schema instead of the required one?

If not, no biggie, but needed to ask since I wanted to use an already established application and add a caldav feed to it.

Thanks!

**Comment by cuchac** [comment]
Hi, 
all the models in django-caldav are abstract and the whole interface is built using ICalFeed that serves as a mediator between your models and feed. So you can use whatever models you want.

**Comment by cuchac** [comment]
For example: [example/our_calendar/views.py](../tree/master/example/our_calendar/views.py) there you can see mapping between model fields and CalDAV output. You can create your own class inheriting from CalDavFeedView. Don't forget to set it to CalDavView.feed_view parameter.
