### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by laudrup** [wpj-cz/django-caldav#5]
I would like to use this project to get caldav integration with my django website, but it seems like this project is very much dead.

Currently, it doesn't work with Django 2 and Python 3, but I have made the required changes locally that seems to fix that.

Would you be interested in pull requests or alternatively having me taking over maintainership of this project?

Thanks a lot and kind regards,

Kasper Laudrup

**Comment by cuchac** [comment]
Hi,

we don't use this project anymore. I think there is no problem in sharing or transferring the project.

**Comment by laudrup** [comment]
Hi @cuchac,

Thanks for the quick reply.

I'll get back to you once I have something that is in some kind of working condition, then we can take it from there.

I wouldn't mind taking over maintenance of this project and the package on PIP if that's OK with you.

Kind regards,

Kasper Laudrup

**Comment by laudrup** [comment]
Hi again,

I've created a fork and added a few commits [here](https://github.com/laudrup/django-caldav).

The commits where mostly related to making the code work with python 3 as well as django 2 and adding a unittest for ensuring that the library can at least be imported.

I would be happy to maintain this library (since I intend to use it for another project). If it's OK with you, could you transfer ownership of the PyPi project to [me](https://pypi.org/user/laudrup/)?

Also, if it's OK that I maintain this, would you prefer to remain owner(s) of the copyright so we share it, or would you prefer transferring that to me? I don't really care either way, it's completely up to you.

Thanks a lot and kind regards,

Kasper Laudrup

**Comment by cuchac** [comment]
Hi,
sorry for this terrible delay :-( I've made you owner of both github and PyPi.

**Comment by laudrup** [comment]
Hi again,

Sorry for my late reply as well.

Thanks a lot. I'll have a look at it and at least update the repository with the changes I've made.
